---

# First, we ensure all of the Ansible inventory details are entered
# in the /etc/hosts file on the nodes.
- name: Ensure inventory hosts in hosts file
  hosts: all
  become: true
  roles:
    - role: bertvv.hosts
      tags: hosts

# Then we install a MySQL server and the Zabbix Server.
- name: Ensure Zabbix server
  hosts: zabbix-server
  become: true

  roles:
    - role: geerlingguy.mysql
      tags: mysql
    - role: community.zabbix.zabbix_server
      tags:
        - zabbix
        - zabbix-server

  tasks:
    - name: Correct History tables
      tags:
        - zabbix
        - zabbix-server
        - history
      block:
        - name: Stop Zabbix server
          ansible.builtin.service:
            name: zabbix-server
            state: stopped

        - name: Upgrade to numeric values of extended range
          community.mysql.mysql_query:
            login_db: zabbix-server
            login_unix_socket: /run/mysqld/mysqld.sock
            query: |
              ALTER TABLE trends
                MODIFY value_min DOUBLE PRECISION DEFAULT '0.0000' NOT NULL,
                MODIFY value_avg DOUBLE PRECISION DEFAULT '0.0000' NOT NULL,
                MODIFY value_max DOUBLE PRECISION DEFAULT '0.0000' NOT NULL;
              ALTER TABLE history MODIFY value DOUBLE PRECISION DEFAULT '0.0000' NOT NULL;

        - name: Correct UI config
          ansible.builtin.lineinfile:
            path: /usr/share/zabbix/conf/zabbix.conf.php
            search_string: "$DB['DOUBLE_IEEE754'] = true;"
            insertbefore: '\?\>'
            line: $DB['DOUBLE_IEEE754'] = true;

        - name: Start Zabbix server
          ansible.builtin.service:
            name: zabbix-server
            state: started

# Since the Zabbix Server by default does not have a frontend, let's install
# Apache, PHP and then the Zabbix Web service
- name: Ensure Zabbix web
  hosts: zabbix-server
  become: true

  roles:
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php
      tags: php
    - role: community.zabbix.zabbix_web
      tags:
        - zabbix
        - zabbix-server

# After that, we ensure that our zabbix-client machines have the zabbix-agent2
# installed and configured. We also install a zabbix-agent2 on the server. Then
# clients will also be added to the Zabbix host group Linux servers and linked
# to the appropriate template
- name: Ensure Zabbix agent2 installation
  hosts: zabbix_clients
  become: true

  roles:
    - role: community.zabbix.zabbix_agent
      tags:
        - zabbix
        - zabbix-clients
